"default": true
"MD033":  # https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md#md033---inline-html
  allowed_elements: 
    - "br"
"MD013": false # https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md#md013---line-length
"MD025": false